- eds/scripts/scripts.js
Added test clientId to test user login from gnav. We can revert this PR after I am done testing or keep the test clientId until we create proper one for this repo.
> Added client id to config object

- eds/components/PartnerCards.js
Resolves: [MWPW-150574](https://jira.corp.adobe.com/browse/MWPW-150574)
Before: https://stage--dx-partners--adobecom.hlx.live/solutionpartners/drafts/dragana/partner-news
After: https://mwpw-150574-chimera-env-improvements--dx-partners--adobecom.hlx.page/solutionpartners/drafts/dragana/partner-news
> mwpw-150547 chimera improvements

- eds/components/PartnerCards.js
Resolves: [MWPW-151250](https://jira.corp.adobe.com/browse/MWPW-151250)
**LInks:**
**Before:** https://stage--dx-partners--adobecom.hlx.page/solutionpartners/drafts/dragana/partner-news
**After:** https://mwpw-151250-decode-cookie--dx-partners--adobecom.hlx.page/solutionpartners/drafts/dragana/partner-news
> Decode cookie

- eds/components/PartnerCards.js
- eds/components/PartnerCardsStyles.js
Resolves: [MWPW-151998](https://jira.corp.adobe.com/browse/MWPW-151998)
**LINKS:**
Before: https://stage--dx-partners--adobecom.hlx.page/solutionpartners/drafts/dragana/partner-news
After: https://mwpw-151998-search-prevent-reload--dx-partners--adobecom.hlx.page/solutionpartners/drafts/dragana/partner-news
> mwpw-151998 - cards search prevent reload on enter

- eds/blocks/knowledge-base-overview/KnowledgeBaseOverview.js
- eds/components/PartnerCards.js
Resolves: [MWPW-151999](https://jira.corp.adobe.com/browse/MWPW-151999)
**LINKS:**
**Before:**
- https://stage--dx-partners--adobecom.hlx.page/solutionpartners/drafts/dragana/partner-news
- https://stage--dx-partners--adobecom.hlx.page/solutionpartners/drafts/dragana/knowledge-overview
**After:**
- https://mwpw-151999-pagination-results-count--dx-partners--adobecom.hlx.page/solutionpartners/drafts/dragana/partner-news
- https://mwpw-151999-pagination-results-count--dx-partners--adobecom.hlx.page/solutionpartners/drafts/dragana/knowledge-overview
**NOTE:**
This change could have an impact on the knowledge-base-overview component, so the pagination for both components should be tested
> Pagination results count

- eds/components/PartnerCards.js
Resolves: [MWPW-152797](https://jira.corp.adobe.com/browse/MWPW-152797)
LINKS:
Before: https://stage--dx-partners--adobecom.hlx.live/solutionpartners/drafts/automation/regression/partner-news
After: https://mwpw-152797-card-title-if-not-authored--dx-partners--adobecom.hlx.live/solutionpartners/drafts/automation/regression/partner-news
> Mwpw 152797 card title if not authored

- eds/blocks/partner-news/PartnerNews.js
- eds/components/PartnerCards.js
Resolves: [MWPW-152074](https://jira.corp.adobe.com/browse/MWPW-152074)
**LINKS:**
**Before:** https://stage--dx-partners--adobecom.hlx.page/solutionpartners/drafts/automation/regression/partner-news
**After:** https://mwpw-152074-never-expires-cards--dx-partners--adobecom.hlx.page/solutionpartners/drafts/automation/regression/partner-news
**NOTE:**
Tag "caas:adobe-partners/collections/news/never-expires" will be active in a few days
> MWPW-152074 - never expires cards; older than 180 days cards;

- eds/blocks/knowledge-base-overview/KnowledgeBaseOverview.js
- eds/components/PartnerCards.js
- eds/scripts/scripts.js
- eds/scripts/utils.js
Resolves MWPW-153015.
LINKS:
Before: https://stage--dx-partners--adobecom.hlx.page/solutionpartners/drafts/dragana/knowledge-overview
After: https://mwpw-153015-cass-envs--dx-partners--adobecom.hlx.page/solutionpartners/drafts/dragana/knowledge-overview
> MWPW-153015: specify if a card collection should use non-prod CaaS on non-prod domains.

- eds/scripts/scripts.js
Resolves: [MWPW-152987](https://jira.corp.adobe.com/browse/MWPW-152987)
-  https://partners.stage.adobe.com/eds/partners-shared/placeholders.json
> MWPW-152987 - placeholders config

- eds/blocks/partner-news/PartnerNews.js
- eds/blocks/partner-news/partner-news.js
Resolves: [MWPW-152128](https://jira.corp.adobe.com/browse/MWPW-152128)
- added **partner news - archive** variation of the block
- updated library: https://mwpw-152128-partner-news-archive--dx-partners--adobecom.hlx.page/docs/library/blocks/partner-news
LINKS:
**Partner news:**
Before: https://stage--dx-partners--adobecom.hlx.page/solutionpartners/drafts/dragana/partner-news
After: https://mwpw-152128-partner-news-archive--dx-partners--adobecom.hlx.page/solutionpartners/drafts/dragana/partner-news
**Partner news archive:**
Before: https://stage--dx-partners--adobecom.hlx.page/solutionpartners/drafts/dragana/partner-news-archive
After: https://mwpw-152128-partner-news-archive--dx-partners--adobecom.hlx.page/solutionpartners/drafts/dragana/partner-news-archive
**NOTE:**
- date picker will …
> MWPW-152128 - partner news archive

- eds/blocks/knowledge-base-overview/KnowledgeBaseOverview.js
- eds/blocks/knowledge-base-overview/knowledge-base-overview.js
- eds/blocks/partner-news/PartnerNews.js
- eds/blocks/partner-news/partner-news.js
- eds/components/NewsCard.js
- eds/components/PartnerCards.js
- eds/components/PartnerCardsStyles.js
- eds/components/PartnerCardsWithDateFilter.js
- eds/scripts/utils.js
- test/blocks/knowledge-base-overview/knowledge-base-overview.test.js
- test/blocks/partner-news/partner-news.test.js
**Resolves:** [MWPW-153922](https://jira.corp.adobe.com/browse/MWPW-153922)
- created a common component, **PartnerCardsWithDateFilter** (since both components , partner news and knowledge base have date filter)
- dafault cardsPerPage for knowledge base is 12
- NewsCard is moved to separated file
- formatDate method moved to utils
- fixed basic eslint errors
- 
**LINKS:**
**Before:**
- https://stage--dx-partners--adobecom.hlx.page/technologypartners/drafts/dragana/knowledge-overview
- https://stage--dx-partners--adobecom.hlx.page/solutionpartners/drafts/dragana/partner-news
**After:**
- https://mwpw-153922-knowledge-date-filter--dx-partners--adobecom.hlx.page/technologypartners/drafts/dragana/knowledge-overview
- https://mwpw-153922-knowledge-date-filter--dx-partners--adobecom.hlx.page/sol …
> MWPW-153922 - knowledge base overview date filter

- eds/components/PartnerCardsStyles.js
**Resolves:** [MWPW-157066](https://jira.corp.adobe.com/browse/MWPW-157066)
**LINKS:**
- **Before**: https://stage--dx-partners--adobecom.hlx.page/solutionpartners/drafts/dragana/partner-news?geourouting=off
- **After**: https://mwpw-157066-sort-behind-profile-drop--dx-partners--adobecom.hlx.page/solutionpartners/drafts/dragana/partner-news?geourouting=off
> MWPW-157066 - sort drop behind profile drop

- eds/components/PartnerCards.js
**Resolves:** [MWPW-160144](https://jira.corp.adobe.com/browse/MWPW-160144)
**LINKS:**
**Before:** https://stage--dx-partners--adobecom.hlx.page/solutionpartners/drafts/automation/regression/partner-news?filters=yes&region=americas&georouting=off
**After:** https://mwpw-160144-arbitrary-fix--dx-partners--adobecom.hlx.page/solutionpartners/drafts/automation/regression/partner-news?filters=yes&region=americas&georouting=off
> MWPW-160144 - arbitrary fix

- .github/workflows/run-nala-on-dx.yml
- .github/workflows/run-nala.yml
- README.md
- eds/scripts/utils.js
- nala/blocks/news/news.test.js
- nala/blocks/signin/signin.test.js
- nala/utils/global.setup.js
- nala/utils/nala.run.js
- playwright.config.js
- run.sh
- test/blocks/knowledge-base-overview/mocks/cards.json
- test/blocks/partner-news/mocks/cards.json
- test/scripts/mocks/gnav-personalization.html
- test/scripts/utils.test.js
Based on https://www.aem.live/developer/upgrade, updated code references to .hlx to use .aem, with exception for announcement-preview, were we are supporting both aem and hlx for now (since we should resend announcements to caas and delete old announcements) and in script/utils.js (i guess we would clean up this once when swap is finished).
Todo
- Detailed QA 
- Merge
- update github secret (rename it from HLX_API_KEY to AEM_API_KEY)
- Swap origin on the akamai level to consume aem.page and aem.live
- Once origins are switched, remove references to hlx.live or hlx.page from the codebase
also after merging 
Set following properties in Sharepoint (and update host property):
cdn.live.host: main--{ repo }--{ owner }.aem.live
cdn.preview.host: main--{ repo }--{ owner }.aem.page …
> MWPW-167115-hlx5

- .github/workflows/run-nala-on-dx.yml
- eds/components/SinglePartnerCard.js
- nala/blocks/news/news.test.js
- nala/blocks/signin/signin.spec.js
testing url: https://triggernala--dx-partners--adobecom.aem.page/solutionpartners/drafts/dragana/partner-news
> fixing nala tests

- eds/blocks/utils/utils.js
- eds/components/SinglePartnerCard.js
testing url: https://mwpw-167873-sync-utils--dx-partners--adobecom.hlx.page/solutionpartners/drafts/dragana/partner-news
> sync code with DME repository

- tools/sidekick/config.json
Test url:
https://MWPW-167901-hlxsidekick--dx-partners--adobecom.hlx.live/solutionpartners/
> MWPW-167901-point sidekick to hlx5

- eds/components/PartnerCards.js
sync with dme
Test url: 
https://MWPW-167524-draft-items-fix--dx-partners--adobecom.hlx.live/solutionpartners/drafts/automation/regression/partner-news
> MWPW-167524-draft items fix

- eds/blocks/partners-navigation/features/breadcrumbs/breadcrumbs.js
- eds/blocks/partners-navigation/features/profile/dropdown.js
- eds/blocks/partners-navigation/features/search/gnav-search.js
- eds/blocks/partners-navigation/partners-navigation.js
- eds/blocks/partners-navigation/utilities/utilities.js
resolves: https://jira.corp.adobe.com/browse/MWPW-167030
follow up for: https://github.com/adobecom/milo/pull/3591
DO NOT MERGE UNTIL ABOVE PR IS MERGED
update: milo pr is merged but release pr in which it is included is still not merged: https://github.com/adobecom/milo/pull/3718 , so waiting on it
test url:
https://mwpw-167030--dx-partners--adobecom.hlx.page/
https://mwpw-167030--dx-partners--adobecom.hlx.page/solutionpartners/drafts/sonja/mwpw165786/pages/home
https://mwpw-167030--dx-partners--adobecom.hlx.page/solutionpartners/drafts/sonja/mwpw165786/pages/home?milolibs=move-federal-code--milo--mokimo
> MWPW-167030-follow up for milo refactoring of federals

- eds/scripts/rewriteLinks.js
- test/scripts/rewriteLinks.jest.js
https://jira.corp.adobe.com/browse/MWPW-169484
URL for testing:
- https://MWPW-169484-url-rewriting-main--dx-partners--adobecom.aem.page/solutionpartners/
> MWPW-169484 prevent url rewriting on milo main branch

- eds/scripts/utils.js
- test/scripts/utils.jest.js
- test/scripts/utils.test.js
URL for testing:
- https://mwpw-169659--dx-partners--adobecom.aem.page/
> MWPW-169659-use www.adobe instead milo.adobe for prod/stage libs

- eds/scripts/utils.js
- tools/sidekick/config.json
Test url:
https://mwpw-167901-hlx4-cleanup--dx-partners--adobecom.aem.page/
> MWPW-167901-remove hlx4 refs

- nala/blocks/smoke-test/smoke.page.js
- nala/blocks/smoke-test/smoke.spec.js
- nala/blocks/smoke-test/smoke.test.js
Ticket: https://jira.corp.adobe.com/browse/MWPW-168683
Testing url: https://mwpw-168683--dx-partners--adobecom.hlx.page/
> MWPW-168683: Smoke Tests - Cover partner directory pages

- eds/scripts/utils.js
https://MWPW-169588--dx-partners--adobecom.aem.live/
> MWPW-169903-channelpartnerassets in the path is also case for cpp

- eds/blocks/partners-navigation/base.css
- eds/blocks/partners-navigation/dark-nav.css
- eds/blocks/partners-navigation/features/breadcrumbs/breadcrumbs.js
- eds/blocks/partners-navigation/features/profile/dropdown.js
- eds/blocks/partners-navigation/features/search/gnav-search.js
- eds/blocks/partners-navigation/partners-navigation.css
- eds/blocks/partners-navigation/partners-navigation.js
- eds/blocks/partners-navigation/utilities/keyboard/index.js
- eds/blocks/partners-navigation/utilities/keyboard/mainNav.js
- eds/blocks/partners-navigation/utilities/keyboard/mobilePopup.js
- eds/blocks/partners-navigation/utilities/keyboard/popup.js
- eds/blocks/partners-navigation/utilities/menu/menu.css
- eds/blocks/partners-navigation/utilities/menu/menu.js
- eds/blocks/partners-navigation/utilities/utilities.js
Testing url: https://MWPW-168681-gnav--dx-partners--adobecom.aem.live/
> Mwpw 168681 gnav

- eds/blocks/partners-navigation/utilities/menu/menu.js
- eds/scripts/personalization.js
- eds/scripts/personalizationConfigDX.js
- eds/scripts/personalizationUtils.js
large menu fix personalization
have unique set of conditions
testing url: 
https://mwpw-170795--dx-partners--adobecom.aem.live/
> MWPW-170795

- eds/blocks/partners-navigation/utilities/menu/menu.js
- eds/scripts/personalization.js
testing url: https://mwpw-172591--dx-partners--adobecom.aem.page/
> Mwpw 172591

- eds/scripts/personalization.js
- eds/scripts/utils.js
Test-URL: https://mwpw-172591-fix-js-errors--dx-partners--adobecom.aem.page/solutionpartners/drafts/ben/test-news-card
> MWPW-172591: fix JS errors when no profile dropdown is authored

- eds/scripts/personalizationConfigDX.js
- eds/scripts/utils.js
and adding personalization conditions for primary contact and newly registred users
ticket: https://jira.corp.adobe.com/browse/MWPW-172072
URL for testing: https://mwpw-172072--dx-partners--adobecom.aem.page/
> adding check for newly registered users within 30 days

- eds/blocks/partners-navigation/partners-navigation.css
- eds/blocks/partners-navigation/partners-navigation.js
Test-URL: https://mwpw-168681-gnav-links-pos--dx-partners--adobecom.aem.live/solutionpartners/drafts/sonja/gnav-icons/home
> MWPW-168681: CSS adjustments as discussed with Abdel

- eds/scripts/utils.js
Testing-URL: https://mwpw-172072-fix-same-day-partners--dx-partners--adobecom.aem.live/solutionpartners/drafts/illya/personalization/rib-on-page#
> MWPW-172072: fix partners registered on the same day

- eds/scripts/utils.js
- test/scripts/utils.jest.js
- test/scripts/utils.test.js
Test URL: https://MWPW-173369-milo-libs--dx-partners--adobecom.aem.page/
> MWPW-173369-fetch libs from our domain, test updated

- eds/scripts/scripts.js
Testing-URL: https://fix-milo-env-for-preview--dx-partners--adobecom.aem.live/
> set milo env correctly for prod hosts

- eds/components/PartnerCards.js
- eds/components/PartnerCardsStyles.js
- eds/components/SinglePartnerCard.js
- eds/components/SinglePartnerCardHalfHeight.js
- test/blocks/dx-card-collection/dx-card-collection.test.js
[(https://jira.corp.adobe.com/browse/MWPW-172013)]
Test url: https://mwpw-172013-caas-variations--dx-partners--adobecom.aem.page/solutionpartners/drafts/dejanbozic/caas/dx-card-collection
- implemented new design for half height card as the one from this link -> https://milo.adobe.com/tools/caas#~~H4sIAAAAAAAACqWOMQvCMBQG/0r55oxOGRW3oh06CCXDM3mGQJqUvASE0v8uVQd3txvu4FbYHCPbGnK60MzQON/6LlJyIfluIc8C9SONocbdEpqXyJ2l4jrHEnyCwiPEykWgp/XLI3noySjkhRO7a+ozOWhAIdicPsRPG5vjkfyemk39VRuFwtJilYHLQH6/PUBBuJ6ouGMu7v1YS2MFya1Yhp5wJ5tnmO0FpByckhMBAAA=
- new design should appear when author adds new row in block with title **Design** and with value **half height card**
> MWPW-172013: caas variations for featured cards half height add
